name: CI - Cloud

# Controls when the action will run. 
on:
  push:
    paths: 
      - 'cloud/**'
    branches: [main]
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
        working-directory: ./cloud/functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: "default"
          PROJECT_PATH: "./cloud"
