name: CI - Mobile

on:
  push:
    paths: 
      - 'mobile/**'
      - 'mobile/*.iOS*/**'
      - '.github/workflows/mobile-android.yml'
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  APK_ARTIFACT: ZwiftCalendar.apk 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build Android project
      run: msbuild mobile/Zwift.Calendar.Mobile.Android/Zwift.Calendar.Mobile.Android.csproj /target:SignAndroidPackage /restore:true /property:Configuration=Release 
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: env.APK_ARTIFACT
        path: mobile/Zwift.Calendar.Mobile.Android/bin/Release/*Signed.apk
        
  publish:
    name: Publish APK
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download APK artifact
      uses: actions/download-artifact@v2
      with:
        name: env.APK_ARTIFACT
    - name: Upload to Visual Studio App Centre
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: HarryHarris/Zwift-Calendar
        token: ${{ secrets.APP_CENTER_TOKEN }}  
        group: Tests
        file: "$APK_ARTIFACT"
        notifyTesters: true
        debug: false      
        releaseNotes: "Hello World"  
